#ifndef _LINUX_LEICAEFI_DEFS_H
#define _LINUX_LEICAEFI_DEFS_H

#include <linux/types.h>

// Registers
#define LEICAEFI_REG_MOD_ID ((u8)0x00)
#define LEICAEFI_REG_MOD_REGV ((u8)0x01)
#define LEICAEFI_REG_MOD_FWV ((u8)0x02)
#define LEICAEFI_REG_MOD_LDRV ((u8)0x03)
#define LEICAEFI_REG_MOD_SCRATCH ((u8)0x04)
#define LEICAEFI_REG_FLASH_CTRL ((u8)0x05)
#define LEICAEFI_REG_FLASH_ADDR ((u8)0x06)
#define LEICAEFI_REG_FLASH_DATA ((u8)0x07)
#define LEICAEFI_REG_MOD_IE ((u8)0x08)
#define LEICAEFI_REG_MOD_IFG ((u8)0x09)
#define LEICAEFI_REG_MOD_ERR ((u8)0x0A)
#define LEICAEFI_REG_MOD_HW ((u8)0x0B)
#define LEICAEFI_REG_CMD_CTRL ((u8)0x0C)
#define LEICAEFI_REG_CMD_DATA ((u8)0x0D)
#define LEICAEFI_REG_KEY_DATA ((u8)0x0E)
#define LEICAEFI_REG_TEST ((u8)0x0F)
#define LEICAEFI_REG_PWR_SRC_STATUS ((u8)0x10)
#define LEICAEFI_REG_PWR_STATUS ((u8)0x11)
#define LEICAEFI_REG_PWR_CTRL ((u8)0x12)
#define LEICAEFI_REG_PWR_SETTINGS ((u8)0x13)
#define LEICAEFI_REG_PWR_SRC_STATUS2 ((u8)0x14)
#define LEICAEFI_REG_PWR_VPOE1 ((u8)0x17)
#define LEICAEFI_REG_PWR_VEXT1 ((u8)0x18)
#define LEICAEFI_REG_PWR_VEXT2 ((u8)0x19)
#define LEICAEFI_REG_PWR_VBAT1 ((u8)0x1A)
#define LEICAEFI_REG_PWR_VLINE ((u8)0x1B)
#define LEICAEFI_REG_TEMP_DATA ((u8)0x1F)
#define LEICAEFI_REG_DEV_STATUS0 ((u8)0x20)
#define LEICAEFI_REG_DEV_STATUS1 ((u8)0x21)
#define LEICAEFI_REG_DEV_STATUS ((u8)0x22)
#define LEICAEFI_REG_DEV_CTRL ((u8)0x23)
#define LEICAEFI_REG_LED_STATUS ((u8)0x24)
#define LEICAEFI_REG_LED_CTRL1 ((u8)0x25)
#define LEICAEFI_REG_LED_CTRL2 ((u8)0x26)
#define LEICAEFI_REG_DBG_LOG ((u8)0x27)
#define LEICAEFI_REG_BAT_1_STATUS ((u8)0x28)
#define LEICAEFI_REG_BAT_1_RSOC ((u8)0x29)
#define LEICAEFI_REG_SMB_REQUEST ((u8)0x30)
#define LEICAEFI_REG_SMB_STATUS ((u8)0x31)
#define LEICAEFI_REG_SMB_CTRL ((u8)0x32)
#define LEICAEFI_REG_SMB_DATA ((u8)0x33)
#define LEICAEFI_REG_SOB_REQUEST ((u8)0x34)
#define LEICAEFI_REG_SOB_STATUS ((u8)0x35)
#define LEICAEFI_REG_SOB_CTRL ((u8)0x36)
#define LEICAEFI_REG_SOB_DATA ((u8)0x37)
#define LEICAEFI_REG_COM_1_ID ((u8)0x38)
#define LEICAEFI_REG_COM_2_ID ((u8)0x39)
#define LEICAEFI_REG_COM_3_ID ((u8)0x3A)
#define LEICAEFI_REG_IFLASH_ADDR ((u8)0x3E)
#define LEICAEFI_REG_IFLASH_DATA ((u8)0x3F)

// I2C/SMBUS interface bits
#define LEICAEFI_REGNO_MASK ((u8)0x3F)      // bits 0-5
#define LEICAEFI_SCBIT_MASK ((u8)(1 << 6))  // bit 6
#define LEICAEFI_SCBIT_SET ((u8)(1 << 6))
#define LEICAEFI_SCBIT_CLEAR ((u8)(0 << 6))
#define LEICAEFI_SCBIT_UNUSED ((u8)(0 << 6))
#define LEICAEFI_RWBIT_MASK ((u8)(1 << 7))  // bit 7
#define LEICAEFI_RWBIT_READ ((u8)(1 << 7))
#define LEICAEFI_RWBIT_WRITE ((u8)(0 << 7))

// IRQ bits
#define LEICAEFI_IRQBIT_ERR (1 << 0)
#define LEICAEFI_IRQBIT_FLASH (1 << 1)
#define LEICAEFI_IRQBIT_KEY (1 << 4)
#define LEICAEFI_IRQBIT_GCC (1 << 5)
#define LEICAEFI_IRQBIT_CBL (1 << 6)
#define LEICAEFI_IRQBIT_SRC (1 << 7)
#define LEICAEFI_IRQBIT_PWR (1 << 8)
#define LEICAEFI_IRQBIT_DEV (1 << 9)
#define LEICAEFI_IRQBIT_SMB (1 << 10)
#define LEICAEFI_IRQBIT_OW (1 << 11)
#define LEICAEFI_IRQBIT_COM (1 << 12)
#define LEICAEFI_IRQBIT_LED (1 << 13)

// MOD_ID platform info
#define LEICAEFI_PLATFORM_SHIFT (12)
#define LEICAEFI_PLATFORM_MASK (0x7)
#define LEICAEFI_PLATFORM_SYSTEM1300 (0)
#define LEICAEFI_PLATFORM_SYSTEM1500 (1)

// MOD_ID project info
#define LEICAEFI_PROJECT_SHIFT (4)
#define LEICAEFI_PROJECT_MASK (0xF)
#define LEICAEFI_PROJECT_SKYMASTER (6)

// MOD_ID processor info
#define LEICAEFI_PROCESSOR_SHIFT (0)
#define LEICAEFI_PROCESSOR_MASK (0xF)
#define LEICAEFI_PROCESSOR_EFI (1)

// MOD_LDRV/FMV version
#define LEICAEFI_VERSION_RELEASE_SHIFT (12)
#define LEICAEFI_VERSION_RELEASE_MASK (0xF)
#define LEICAEFI_VERSION_VERSION_SHIFT (8)
#define LEICAEFI_VERSION_VERSION_MASK (0xF)
#define LEICAEFI_VERSION_SUBVERSION_SHIFT (0)
#define LEICAEFI_VERSION_SUBVERSION_MASK (0xFF)

// MOD_HW elements
#define LEICAEFI_PCBA_VARIANT_SHIFT (0)
#define LEICAEFI_PCBA_VARIANT_MASK (0xF)
#define LEICAEFI_PCBA_VERSION_SHIFT (4)
#define LEICAEFI_PCBA_VERSION_MASK (0xF)

#endif /*_LINUX_LEICAEFI_DEFS_H*/
