#ifndef _LINUX_LEICAEFI_DEFS_H
#define _LINUX_LEICAEFI_DEFS_H

#include <linux/types.h>

// Registers
#define LEICAEFI_REG_MOD_ID ((__u8)0x00)
#define LEICAEFI_REG_MOD_REGV ((__u8)0x01)
#define LEICAEFI_REG_MOD_FWV ((__u8)0x02)
#define LEICAEFI_REG_MOD_LDRV ((__u8)0x03)
#define LEICAEFI_REG_MOD_SCRATCH ((__u8)0x04)
#define LEICAEFI_REG_FLASH_CTRL ((__u8)0x05)
#define LEICAEFI_REG_FLASH_ADDR ((__u8)0x06)
#define LEICAEFI_REG_FLASH_DATA ((__u8)0x07)
#define LEICAEFI_REG_MOD_IE ((__u8)0x08)
#define LEICAEFI_REG_MOD_IFG ((__u8)0x09)
#define LEICAEFI_REG_MOD_ERR ((__u8)0x0A)
#define LEICAEFI_REG_MOD_HW ((__u8)0x0B)
#define LEICAEFI_REG_CMD_CTRL ((__u8)0x0C)
#define LEICAEFI_REG_CMD_DATA ((__u8)0x0D)
#define LEICAEFI_REG_KEY_DATA ((__u8)0x0E)
#define LEICAEFI_REG_TEST ((__u8)0x0F)
#define LEICAEFI_REG_PWR_SRC_STATUS ((__u8)0x10)
#define LEICAEFI_REG_PWR_STATUS ((__u8)0x11)
#define LEICAEFI_REG_PWR_CTRL ((__u8)0x12)
#define LEICAEFI_REG_PWR_SETTINGS ((__u8)0x13)
#define LEICAEFI_REG_PWR_SRC_STATUS2 ((__u8)0x14)
#define LEICAEFI_REG_PWR_VPOE1 ((__u8)0x17)
#define LEICAEFI_REG_PWR_VEXT1 ((__u8)0x18)
#define LEICAEFI_REG_PWR_VEXT2 ((__u8)0x19)
#define LEICAEFI_REG_PWR_VBAT1 ((__u8)0x1A)
#define LEICAEFI_REG_PWR_VLINE ((__u8)0x1B)
#define LEICAEFI_REG_TEMP_DATA ((__u8)0x1F)
#define LEICAEFI_REG_DEV_STATUS0 ((__u8)0x20)
#define LEICAEFI_REG_DEV_STATUS1 ((__u8)0x21)
#define LEICAEFI_REG_DEV_STATUS ((__u8)0x22)
#define LEICAEFI_REG_DEV_CTRL ((__u8)0x23)
#define LEICAEFI_REG_LED_STATUS ((__u8)0x24)
#define LEICAEFI_REG_LED_CTRL1 ((__u8)0x25)
#define LEICAEFI_REG_LED_CTRL2 ((__u8)0x26)
#define LEICAEFI_REG_DBG_LOG ((__u8)0x27)
#define LEICAEFI_REG_BAT_1_STATUS ((__u8)0x28)
#define LEICAEFI_REG_BAT_1_RSOC ((__u8)0x29)
#define LEICAEFI_REG_SMB_REQUEST ((__u8)0x30)
#define LEICAEFI_REG_SMB_STATUS ((__u8)0x31)
#define LEICAEFI_REG_SMB_CTRL ((__u8)0x32)
#define LEICAEFI_REG_SMB_DATA ((__u8)0x33)
#define LEICAEFI_REG_SOB_REQUEST ((__u8)0x34)
#define LEICAEFI_REG_SOB_STATUS ((__u8)0x35)
#define LEICAEFI_REG_SOB_CTRL ((__u8)0x36)
#define LEICAEFI_REG_SOB_DATA ((__u8)0x37)
#define LEICAEFI_REG_COM_1_ID ((__u8)0x38)
#define LEICAEFI_REG_COM_2_ID ((__u8)0x39)
#define LEICAEFI_REG_COM_3_ID ((__u8)0x3A)
#define LEICAEFI_REG_IFLASH_ADDR ((__u8)0x3E)
#define LEICAEFI_REG_IFLASH_DATA ((__u8)0x3F)

// I2C/SMBUS interface bits
#define LEICAEFI_REGNO_MASK ((__u8)0x3F) // bits 0-5
#define LEICAEFI_SCBIT_MASK ((__u8)(1 << 6)) // bit 6
#define LEICAEFI_SCBIT_SET ((__u8)(1 << 6))
#define LEICAEFI_SCBIT_CLEAR ((__u8)(0 << 6))
#define LEICAEFI_SCBIT_UNUSED ((__u8)(0 << 6))
#define LEICAEFI_RWBIT_MASK ((__u8)(1 << 7)) // bit 7
#define LEICAEFI_RWBIT_READ ((__u8)(1 << 7))
#define LEICAEFI_RWBIT_WRITE ((__u8)(0 << 7))

// IRQ bits
#define LEICAEFI_IRQBIT_ERR (1 << 0)
#define LEICAEFI_IRQBIT_FLASH (1 << 1)
#define LEICAEFI_IRQBIT_KEY (1 << 4)
#define LEICAEFI_IRQBIT_GCC (1 << 5)
#define LEICAEFI_IRQBIT_CBL (1 << 6)
#define LEICAEFI_IRQBIT_SRC (1 << 7)
#define LEICAEFI_IRQBIT_PWR (1 << 8)
#define LEICAEFI_IRQBIT_DEV (1 << 9)
#define LEICAEFI_IRQBIT_SMB (1 << 10)
#define LEICAEFI_IRQBIT_OW (1 << 11)
#define LEICAEFI_IRQBIT_COM (1 << 12)
#define LEICAEFI_IRQBIT_LED (1 << 13)

// ERR bits
#define LEICAEFI_ERRBIT_IA (1 << 0)
#define LEICAEFI_ERRBIT_FLASH (1 << 1)
#define LEICAEFI_ERRBIT_KEY (1 << 4)
#define LEICAEFI_ERRBIT_GCE (1 << 5)
#define LEICAEFI_ERRBIT_PWR (1 << 8)
#define LEICAEFI_ERRBIT_DEV (1 << 9)
#define LEICAEFI_ERRBIT_SMB (1 << 10)
#define LEICAEFI_ERRBIT_OW (1 << 11)
#define LEICAEFI_ERRBIT_COM (1 << 12)
#define LEICAEFI_ERRBIT_HMI (1 << 13)

// FLASH_CTRL bits
#define LEICAEFI_FLASHCTRLBIT_EIFLASH (1 << 0)
#define LEICAEFI_FLASHCTRLBIT_SIFLASH (1 << 1)
#define LEICAEFI_FLASHCTRLBIT_CIFLASH (1 << 2)
#define LEICAEFI_FLASHCTRLBIT_FWCHK (1 << 8)
#define LEICAEFI_FLASHCTRLBIT_LDRCHK (1 << 9)
#define LEICAEFI_FLASHCTRLBIT_WREN (1 << 11)
#define LEICAEFI_FLASHCTRLBIT_SWITCH (1 << 14)
#define LEICAEFI_FLASHCTRLBIT_ESEC (1 << 15)

// MOD_ID mode bit
#define LEICAEFI_MODID_MODE_SHIFT (15)
#define LEICAEFI_MODID_MODE_MASK (0x1)
#define LEICAEFI_MODID_MODE_FIRMWARE (0)
#define LEICAEFI_MODID_MODE_LOADER (1)

// MOD_ID platform info
#define LEICAEFI_MODID_PLATFORM_SHIFT (12)
#define LEICAEFI_MODID_PLATFORM_MASK (0x7)
#define LEICAEFI_MODID_PLATFORM_SYSTEM1300 (0)
#define LEICAEFI_MODID_PLATFORM_SYSTEM1500 (1)

// MOD_ID project info
#define LEICAEFI_MODID_PROJECT_SHIFT (4)
#define LEICAEFI_MODID_PROJECT_MASK (0xF)
#define LEICAEFI_MODID_PROJECT_SKYMASTER (6)

// MOD_ID processor info
#define LEICAEFI_MODID_PROCESSOR_SHIFT (0)
#define LEICAEFI_MODID_PROCESSOR_MASK (0xF)
#define LEICAEFI_MODID_PROCESSOR_EFI (1)

// MOD_LDRV/FMV version
#define LEICAEFI_VERSION_RELEASE_SHIFT (12)
#define LEICAEFI_VERSION_RELEASE_MASK (0xF)
#define LEICAEFI_VERSION_VERSION_SHIFT (8)
#define LEICAEFI_VERSION_VERSION_MASK (0xF)
#define LEICAEFI_VERSION_SUBVERSION_SHIFT (0)
#define LEICAEFI_VERSION_SUBVERSION_MASK (0xFF)

// MOD_HW elements
#define LEICAEFI_PCBA_VARIANT_SHIFT (0)
#define LEICAEFI_PCBA_VARIANT_MASK (0xF)
#define LEICAEFI_PCBA_VERSION_SHIFT (4)
#define LEICAEFI_PCBA_VERSION_MASK (0xF)

// POWER_SRC_STATUS bits
#define LEICAEFI_POWERSRCBIT_BAT1VAL (1 << 0)
#define LEICAEFI_POWERSRCBIT_EXT1VAL (1 << 1)
#define LEICAEFI_POWERSRCBIT_EXT2VAL (1 << 2)
#define LEICAEFI_POWERSRCBIT_POE1VAL (1 << 3)
#define LEICAEFI_POWERSRCBIT_CHGVAL (1 << 6)
#define LEICAEFI_POWERSRCBIT_CHGREADY (1 << 7)
#define LEICAEFI_POWERSRCBIT_BAT1ACT (1 << 8)
#define LEICAEFI_POWERSRCBIT_EXT1ACT (1 << 9)
#define LEICAEFI_POWERSRCBIT_EXT2ACT (1 << 10)
#define LEICAEFI_POWERSRCBIT_POE1ACT (1 << 11)
#define LEICAEFI_POWERSRCBIT_CHGACT (1 << 14)
#define LEICAEFI_POWERSRCBIT_UVLO (1 << 15)

// Subsystems
#define LEICAEFI_CMD_BATTERY1_READMSG_MASK (0x8A00)
#define LEICAEFI_CMD_BATTERY1_WRITEMSG_MASK (0x8A00)

// Battery subsystem messages
#define LEICAEFI_BAT_MSG_TEMPERATURE (0x08)
#define LEICAEFI_BAT_MSG_VOLTAGE (0x09)
#define LEICAEFI_BAT_MSG_CURRENT (0x0A)
#define LEICAEFI_BAT_MSG_AVERAGE_CURRENT (0x0B)
#define LEICAEFI_BAT_MSG_RUN_TIME_TO_EMPTY (0x11)
#define LEICAEFI_BAT_MSG_AVERAGE_TIME_TO_EMPTY (0x12)
#define LEICAEFI_BAT_MSG_AVERAGE_TIME_TO_FULL (0x13)
#define LEICAEFI_BAT_MSG_CYCLE_COUNT (0x17)

#endif /*_LINUX_LEICAEFI_DEFS_H*/
